GET http://127.0.0.1:8000/api/categoria

### guardar categoria

POST http://127.0.0.1:8000/api/categoria
Content-Type: application/json
Accept: application/json

{
    "nombre": "Cat 2",
    "detalle": "Categoría 2"
}

### mostrar categoria

GET http://127.0.0.1:8000/api/categoria/2

### modificar
PUT http://127.0.0.1:8000/api/categoria/2
Content-Type: application/json
Accept: application/json

{
    "nombre": "ELECTRONICOS MODIFICADO",
    "detalle": "Electronicos para PC actualizado"
}

### eliminar
DELETE http://127.0.0.1:8000/api/categoria/1